import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const merriweatherSans = localFont({
  src: "./fonts/Merriweather_Sans/MerriweatherSans-VariableFont_wght.ttf",
  variable: "--font-merriweather-sans",
  weight: "300 800",
});

const spaceMono = localFont({
  src: [
    {
      path: "./fonts/Space_Mono/SpaceMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Space_Mono/SpaceMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${merriweatherSans.variable} ${spaceMono.variable}`}>
      {children}
      </body>
      </html>
  );
}